server:
  port: 8080

api :
  eKatalogService-url: localhost:8000/api/items/
  userService-url: localhost:8001/api/users/

telegram:
  bot-name: ${botName}
  api-key: ${botToken}
  bot-owner: ${botOwner}