server:
  port: 8002

spring:
  application:
    name: notification-service

api :
  eKatalogService-url: localhost:8000/api/items/
  userService-url: localhost:8001/api/users/
  telegramService-url: localhost:8080/telegram/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
